# Generated by Django 5.1.5 on 2025-02-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='school_year',
            new_name='class_of',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='athletes.athlete'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='athletes.athlete'),
        ),
    ]
