# Generated by Django 5.1.5 on 2025-02-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_rename_school_year_athlete_class_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height_inches',
            field=models.IntegerField(verbose_name='Height (in)'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='interests',
            field=models.TextField(verbose_name='Interests (one per line)'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight_lbs',
            field=models.FloatField(verbose_name='Weight (lbs)'),
        ),
        migrations.CreateModel(
            name='SportStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_stats', to='athletes.sport')),
            ],
        ),
        migrations.DeleteModel(
            name='SportStats',
        ),
    ]
