# Generated by Django 5.1.5 on 2025-02-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athlete_height_inches_alter_athlete_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstat',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='athletes.sport'),
        ),
    ]
