# Generated by Django 5.1.5 on 2025-04-30 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_alter_sportstat_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='gallery',
            field=models.ImageField(blank=True, upload_to='athletes'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='image',
            field=models.ImageField(blank=True, upload_to='athletes'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='athletes')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='athletes.athlete')),
            ],
        ),
    ]
