# Generated by Django 5.1.5 on 2025-04-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='gallery',
        ),
    ]
