# Generated by Django 5.1.5 on 2025-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_remove_athlete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='alt',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
