# Generated by Django 5.1.5 on 2025-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_gallery_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='tags',
            field=models.TextField(default='', verbose_name='Tags (one per line)'),
            preserve_default=False,
        ),
    ]
