# Generated by Django 5.1.5 on 2025-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_athlete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='position',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
