# Generated by Django 5.1.5 on 2025-05-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0010_athlete_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon',
            field=models.CharField(default='tabler:run', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='tags',
            field=models.TextField(verbose_name='Tags (one per line, max 3)'),
        ),
    ]
