# Generated by Django 5.1.5 on 2025-05-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0011_sport_icon_alter_athlete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='tagline',
            field=models.CharField(default='Summary', max_length=64),
            preserve_default=False,
        ),
    ]
